author:
  email: tikismoke@users.noreply.github.com
  homepage: https://github.com/tikismoke/home-assistant-nespressoble
  name: Tikismoke
description: Nespresso ble component
files:
  - custom_components/nespresso/__init__.py
  - custom_components/nespresso/sensor.py
keywords:
  - coffee
  - nespresso
  - homeassistant
  - home-assistant
  - custom-component
  - python
license: MIT License
name: sensor.nespresso
type: component